export const EnumError = Object.freeze({
  //ERRORES DE RESGISTRO Y LOGEO DE USUARIOS
  USER_ALREADY_EXISTS: 1001,
  INVALID_CREDENTIALS: 1002,
  INCOMPLET_FIELDS: 1003,
  //ERRORES DE COMPRA Y VENTA DE PRODUCTOS
  PRODUCT_NOT_FOUND: 2001,
  INSUFFICIENT_STOCK: 2002,
  //CART
  CART_NOT_FOUND: 3001,
  //URL
  URL_NOT_fOUND: 4001,
});
