swagger: 3.0.1
info:
  version: 1.0.0
  title: Session API
  description: API para gestionar sesiones

tags:
  - name: Session
    description: Endpoints para gestionar sesiones

paths:
  /session/current:
    get:
      summary: Obtener información del usuario actual
      tags: [Session]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/InfoDto"
        "401":
          description: Unauthorized
        "500":
          description: Error interno del servidor

definitions:
  InfoDto:
    type: object
    properties:
      firstName:
        type: string
      email:
        type: string
      lastName:
        type: string
      role:
        type: string
    example:
      firstName: John
      email: john@example.com
      lastName: Doe
      role: user
